# Generated by Django 6.0.4 on 2026-04-21 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='airport.airport'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='airport.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airport.route'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airport.flight'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airport.order'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['source'], name='airport_rou_source__8bce3e_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['destination'], name='airport_rou_destina_0dae4c_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['source', 'destination'], name='airport_rou_source__5c8f4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('destination')), _negated=True), name='prevent_same_airport_route'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['route'], name='airport_fli_route_i_b2cc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_time'], name='airport_fli_departu_abe547_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['route', 'departure_time'], name='airport_fli_route_i_baa295_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('flight', 'row', 'seat'), name='unique_ticket_per_seat'),
        ),
    ]
